services:
  seti-file-store:
    image: aelmendorf234/seti-file-store:latest
    container_name: seti-file-store
    pull_policy: always
    restart: unless-stopped
    ports:
      - "8080:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    pull_policy: always
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /home/setiadmin/seti-file-store/db/:/data/db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup --interval 30
    labels:
      - "com.centurylinklabs.watchtower.enable=false"